### ISSUE TITLE
杭州地区，旧版闪讯无法再使用PPPoE。

### ISSUE THREAD

**Issue by HowardEternal** [miao1007/Openwrt-NetKeeper#1]
杭州地区昨天（2015年3月25日）闪讯升级了服务器，旧版的闪讯无法再使用，新版的闪讯会在电脑上安装“必要”驱动，之后才能正常。另外我这儿的学校网络重组，闪讯换用L2TP拨号，LNS地址为183.157.160.5。

**Comment by miao1007** [comment]
能发一下各个平台的下载地址吗。

还有，你们学校的L2TP我不太懂，是学校的内网吗？还是闪讯的拨号？

**Comment by sunflyer** [comment]
L2TP是代理模式。一种VPN协议，在Windows系统仍然使用RAS组件，但是现在一般的路由器都无法做到L2TP协议链接。OPWRT我就不太清楚了
 
 
------------------ Original ------------------

**Comment by miao1007** [comment]
L2TP,PPTP,openVPN,Cisco等乱七八糟的都是支持的，无非就是配一下学校内网的路由表而已

**Comment by miao1007** [comment]
有时间测试一下，我添加杭州的radius了
