### ISSUE TITLE
湖北心跳已经解决

### ISSUE THREAD

**Issue by dxskj** [miao1007/Openwrt-NetKeeper#114]
他们家已经解决湖北心跳【收费50】http://www.xy-wifi.com/

#!/bin/bash
while true
do

ping -c1 123.125.114.144

if [ $? = 0 ];then
usr=$(uci get network.wan.username)
psd=$(uci get network.wan.password)
mac=$(uci get network.wan.macaddr)
ip=$(ip route show | grep 'pppoe-wan  proto kernel' | awk -F' ' '{print $NF}')
echo $usr"!!"$psd"!!"$mac"!!"$ip"!!" > /tmp/HBdata.txt
/etc/rc.button/c
break

else
sleep 60
echo "--------wan is down--------"

fi
done

**Comment by sunflyer** [comment]
这广告打得好。一段无意义的脚本丢这里有何意思？
