### ISSUE TITLE
请问小米路由器能用这个么？

### ISSUE THREAD

**Issue by lycycycycyc** [miao1007/Openwrt-NetKeeper#12]
我最近买了个小米路由器mini，请问能用么

**Comment by lycycycycyc** [comment]
http://downloads.openwrt.org/snapshots/trunk/ 里面没有MT7620A怎么办

**Comment by miao1007** [comment]
http://downloads.openwrt.org/snapshots/trunk/ramips/mt7620/

**Comment by kirito269** [comment]
好像都不行吧……

**Comment by lycycycycyc** [comment]
是需要刷成openwrt的系统么

**Comment by miao1007** [comment]
不推荐原厂的系统，建议刷成官方系统

**Comment by lycycycycyc** [comment]
http://downloads.openwrt.org.cn/PandoraBox/Xiaomi-Mini-R1CM/testing/
这里面的版本可以么

**Comment by miao1007** [comment]
可以

**Comment by lycycycycyc** [comment]
Sat Jun 27 15:19:00 2015 daemon.notice netifd: Interface 'NetKeeper' is setting up now
Sat Jun 27 15:19:01 2015 daemon.info pppd[20938]: Plugin rp-pppoe.so loaded.
Sat Jun 27 15:19:01 2015 daemon.info pppd[20938]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.7
Sat Jun 27 15:19:01 2015 daemon.notice netifd: NetKeeper (20938): /usr/sbin/pppd: File not found
Sat Jun 27 15:19:01 2015 daemon.err pppd[20938]: File not found
Sat Jun 27 15:19:01 2015 daemon.notice netifd: NetKeeper (20938): /usr/sbin/pppd: Couldn't load plugin sxplugin.so
Sat Jun 27 15:19:01 2015 daemon.err pppd[20938]: Couldn't load plugin sxplugin.so
Sat Jun 27 15:19:01 2015 daemon.notice netifd: Interface 'NetKeeper' is now down

**Comment by lycycycycyc** [comment]
这样是除了什么问题？

**Comment by lycycycycyc** [comment]
有人小米路由mini成功的么?为什么我的怎么弄都不行

**Comment by SuperBain** [comment]
我也是和你一样的问题，日志内容也差不多，请问你找到解决方法了吗？

**Comment by lycycycycyc** [comment]
应该是编译时候出的问题，路由器还在我寝室，我放假回家了，就没再研究了

**Comment by lycycycycyc** [comment]
编译时报错，environment variable "STAGING_DIR" not defined

**Comment by miao1007** [comment]
湖北的有人编译好了 http://www.right.com.cn/forum/forum.php?mod=redirect&goto=findpost&ptid=141979&pid=1061829

**Comment by lycycycycyc** [comment]
问题已经解决，当初是因为gcc找错了所以放进路由里面才会出错
