### ISSUE TITLE
那个心跳插件怎么编译啊？

### ISSUE THREAD

**Issue by shitou001** [miao1007/Openwrt-NetKeeper#127]
In file included from main.c:19:0:
netkeeper.h:15:25: fatal error: mbedtls/aes.h: No such file or directory
 #include <mbedtls/aes.h>
                         ^
compilation terminated.
Makefile:9: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by zaqzxc** [comment]
交叉编译

**Comment by shitou001** [comment]
具体怎么搞，那个so文件编译成功了，这个main.c编译出错了

**Comment by sunflyer** [comment]
最好先看代码，别编译错版本了。

**Comment by shitou001** [comment]
原谅我根本看不懂代码😂

**Comment by zaqzxc** [comment]
贴运行make后面代码

**Comment by shitou001** [comment]
@zaqzxc
 /home/xx/luyouqi/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-gcc -o main.o main.c -g -Wall -Wimplicit-function-declaration -I /include/  -c
mipsel-openwrt-linux-uclibc-gcc.bin: warning: environment variable 'STAGING_DIR' not defined
In file included from main.c:19:0:
netkeeper.h:15:25: fatal error: mbedtls/aes.h: No such file or directory
 #include <mbedtls/aes.h>
                         ^
compilation terminated.
Makefile:9: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by sunflyer** [comment]
你还需要mbedtls的库。

**Comment by sunflyer** [comment]
另外呢你没必要去艾特那位，那位估计是湖北的某个商人？

**Comment by Sung-yy** [comment]
@sunflyer 问一下,main.c里的注释里的key有用吗,我编译的时候需要修改吗,还有那个makefile里的change radius在哪里修改啊,需不需要修改?

**Comment by BabyGH** [comment]
@shitou001 您好，我也在尝试编译SO文件，但这个步骤“Read and edit makefile and confnetwork.sh TODOS carefully”只用修改这两个文件吗？makefile中在文本哪处Change Radius还有Change PREFIX1？还请您指点，谢谢哈

**Comment by shitou001** [comment]
搞了几天还是没弄好，我要放弃了，先学好c语言能看懂源码再说

**Comment by BabyGH** [comment]
@shitou001 您那so不是编译好了吗 可以告诉我咋弄吗

**Comment by shitou001** [comment]
搭建好交叉编译环境，根据自己的需要修改需要修改的地方，makefile写的很清楚，然后make all就可以了

**Comment by BabyGH** [comment]
@shitou001 关键是有些地方不知道要不要改 以及怎末该 看不懂啊 您可以加我q一下吗1752167203

**Comment by BabyGH** [comment]
@shitou001 还是编译不成功啊 能教教我吗

**Comment by theflash2017** [comment]
你编译成功了吗？
