### ISSUE TITLE
arm 梅林固件的路由怎么用这个吗？

### ISSUE THREAD

**Issue by lee86** [miao1007/Openwrt-NetKeeper#129]
如题，湖北武汉的，求大佬救命，实在受不了电信了

**Comment by lee86** [comment]
mac版的e信貌似根本不用管当前系统时间，可以直接成功拨号，而且心跳好像只检测5次

**Comment by sunflyer** [comment]
插件都已经在这里了。。自己编译就好了嘛

**Comment by lee86** [comment]
大佬，又没有可能通过Mac版的e信搞出账号啊？因为我在Mac下无论系统时间对不对都可以成功拨号，但是win就不行

**Comment by zaiweijian** [comment]
https://github.com/chingcq/hiwifi-netkeeper和https://github.com/xratzh/hiwifi-netkeeper，你可以去看下
