### ISSUE TITLE
亲测南昌算法依旧可用（暂时？）

### ISSUE THREAD

**Issue by 0es** [miao1007/Openwrt-NetKeeper#131]
**NanChangV32: jiangxi4.0**
`
nanchang_sxplugin:
@$(CC) $(CFLAGS) sxplugin.c -DRADIUS='"jiangxi4.0"' -DPREFIX1="'1'" -shared -o $@.so
`

**Comment by wellCh4n** [comment]
请问，你连接的时候是满速吗？

**Comment by 0es** [comment]
@wellCh4n 是满速。我看到你的issue了，如果拨号成功就和这个算法程序没关系了，不应该有速度问题

**Comment by XiaoLrrr** [comment]
能分享一下江西的so文件吗？谢谢了preect1217@gmail.com
