### ISSUE TITLE
......

### ISSUE THREAD

**Issue by zaqzxc** [miao1007/Openwrt-NetKeeper#137]

**Comment by sunflyer** [comment]
啧啧啧，你当初第一个PR可就是“湖北电信云心跳搭建教程”
自己打自己脸系列？

**Comment by zaqzxc** [comment]
你牛，心跳也不只你一个人会弄，我们这边的易捷校园公司团队也会弄，还开发了自己的APP http://118.178.88.161.

还有云心跳 http://120.25.236.244/ip/

                   http://123.207.13.194/

**Comment by miao1007** [comment]
如果不是为了兴趣，可能连成本都收不回来

**Comment by sunflyer** [comment]
那么问题来了，你现在把人家APP发出来，其实不过也是为了一个目的，你也不过是想做一套云心跳赚钱罢了。

当初在这个项目里面提到“云心跳搭建教程”的是你
现在回来一边说“求开源”一边又说“又不是只有你一个会弄”的也是你

你看你那跳脚的样子，简直可笑。

**Comment by left906080850** [comment]
@sunflyer  暗中观察

**Comment by left906080850** [comment]
啪啪啪，噗噗噗，噗呲噗呲，真TM响

**Comment by x1184** [comment]
前排围观下

**Comment by x1184** [comment]
支持下原开发者，没技术的只会抄代码的这里不适合你
