### ISSUE TITLE
怎么设置断网后，停止自动拨号重连？

### ISSUE THREAD

**Issue by gmfghp** [miao1007/Openwrt-NetKeeper#144]
校园网 账号截获后，拨号成功，一段时间后，可能重新分配ip自动掉线了，然后路由器还在不断的重新拨号，时间长了，这个账号就会被封，所以怎么解决，不自动重新拨号连接的问题 ？貌似已经有通知说这个问题了。求助。

**Comment by huipengly** [comment]
查了资料，试了设置maxfail=1无用，就在脚本里直接检测了，如果断网就关闭pppoe拨号。已更新脚本，可以去测试一下。

**Comment by gmfghp** [comment]
@huipengly 嗯嗯， 太难的编程我不会，只能提提建议了。
