### ISSUE TITLE
山东移动4.9更新算法

### ISSUE THREAD

**Issue by StchaoL** [miao1007/Openwrt-NetKeeper#149]
经测试，在编译shandongmobile_sxplugin.so时，修改makefile使“RADIUS”变量为空字符串，可以使用。

**Comment by zxy4ever** [comment]
那么这意思就是山东移动的4.9版本算法未使用radius字符串或者说该部分为空了？

**Comment by txrtanzi** [comment]
同意，用空 RADIUS 参数编译的 shandongmobile.so 可以在路由器上正常运行

**Comment by miao1007** [comment]
https://github.com/miao1007/Openwrt-NetKeeper/commit/58c75f4b1856815b23c3ef521182e93032c0725c
