### ISSUE TITLE
心跳插件编译问题，已找到原因。

### ISSUE THREAD

**Issue by RuiKylin** [miao1007/Openwrt-NetKeeper#166]
问题是K3 处理器的SDK中 **toolchains** 中没有 **libmbedcrypto.a** 这个文件，无法编译通过。

没接触过C，_**丢人了**_，已解决问题。Orz

**Comment by Destinyzxn** [comment]
我之前编译的时候 也有这个问题 求解答

**Comment by RuiKylin** [comment]
@Destinyzxn  
 **libmbedcrypto.a** 是 **mbed TlS** 的 library 文件。

- 你需要先编译一个 **mbedtls**
   GitHub 上直接搜索 mbedtls

- 编译好 **mbedtls** 之后，再进行心跳插件的编译即可。

**Comment by Destinyzxn** [comment]
编译之后 放进了lib文件夹内 在daonet目录下make 报错
root@VM-111-115-ubuntu:~/Openwrt-NetKeeper/src/DaoNet/DaoNet# make
mipsel-openwrt-linux-gcc  -o main.o main.c -g -Wall -Wimplicit-function-declaration -I /root/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/include/  -c
In file included from main.c:19:0:
netkeeper.h:15:25: fatal error: mbedtls/aes.h: No such file or directory
 #include <mbedtls/aes.h>
                         ^
compilation terminated.
Makefile:8: recipe for target 'main.o' failed
make: *** [main.o] Error 1
查百度说 安装mbedtls库 我也试着安装了 也还是报错

**Comment by RuiKylin** [comment]
你的路由器CPU为MT7620，不需要你自己编译。
项目里有现成的.so文件，至于心跳是江西专用的。
留下的Email通讯OK？

**Comment by Destinyzxn** [comment]
814182054@qq.com
so编译我会
