### ISSUE TITLE
关于武昌地区的奸商

### ISSUE THREAD

**Issue by light499960904** [miao1007/Openwrt-NetKeeper#171]
这群逼人（特指奸商）是真的无耻，本人坐标，WUT（emmmmmmm），他去卖还不负责售后，结果心跳一更新，我QQ炸了，三天两头有人问路由器的逼事，软件发来一看，这尼玛，一脸奸商的样子。这种东西，留个思路，想搞事情的，自然会自己去研究

**Comment by Tomsu2016** [comment]
你的昵称看起来像水军
