### ISSUE TITLE
望支持江西高校2.5v32版本netkeeper

### ISSUE THREAD

**Issue by Sg4Dylan** [miao1007/Openwrt-NetKeeper#18]
原始安装文件及LordPE的dump文件
[http://1drv.ms/1Kv02bJ](http://1drv.ms/1Kv02bJ)

TimeFlag后的字符串
![TimeFlag](https://i.imgur.com/cCAwRPo.png)

**Comment by miao1007** [comment]
理论上，只要替换掉key，就可以运行的

**Comment by Sg4Dylan** [comment]
对不起，有一点忘了说
以往的方法（比如TP系列路由器的特殊拨号模式和[星空助手](https://github.com/xseven007/Netkeeper)
能拨上号但是不能上网

**Comment by miao1007** [comment]
路由表配置错误，心跳开了，第三方固件对PPPoE支持问题，就这三种

**Comment by realityone** [comment]
shareKey = `jiangxi4.0`
prefix = '\r1'

**Comment by Sg4Dylan** [comment]
实测楼上的shareKey和prefix可以用

**Comment by breeeeze** [comment]
拨上号不会断了吗

**Comment by miao1007** [comment]
倒是提交下代码啊~ 我目前对Prefix还不太了解，是`\r\n`这里吗？

**Comment by Sg4Dylan** [comment]
OpenWRT的应该是修改42行和108行吧 = =
但是现在还没到学校没法自己测试，测试shareKey的时候是让同学帮忙的
使用的是这个Windows拨号器 https://github.com/xseven007/Netkeeper 
拨上可以正常使用，不会断开
