### ISSUE TITLE
关于 Netkeeper 新算法

### ISSUE THREAD

**Issue by zuishikonghuan** [miao1007/Openwrt-NetKeeper#185]
首先对这个曾经帮助我的项目的维护者表示衷心感谢

我不用路由器，我以前一直将本项目的代码移植到 Debian 系统的笔记本上使用

最近，山东移动似乎已经更新，将 RADIUS 设置为空的方法已经好几天无法拨号了，现在我不得不使用手机流量共享热点来上网

我也把拦截账户的 nk4.sh 移植到了我的 debian 笔记本上，但是我很失望的是，Netkeeper 的客户端有反虚拟机机制，我无法在虚拟机（win7）中启动客户端，也就是说我没有办法启动一次拨号。

我让我的室友帮忙连上帮我拨号一次，发现可用，但不是长久之计，我总不能一天好几次每次开机都让别人帮忙折腾吧。因为他们也有自己的拨号。

购买路由器也是没有用的，因为 Netkeeper 不但无法 wine 运行，而且无法虚拟机运行。我现在无计可施。

//而我又不会逆向，硬着头皮搜教程折腾了一天什么都没弄明白，连 Netkeeper 的反虚拟机都没搞清楚是怎么实现的。。。

因此我想问一下，请问你们还会对新算法进行适配吗，如果你们已经放弃适配新算法，也就是说没有新算法可用的话，我就只好选择退掉宽带了。

再次感谢你们

**Comment by akkuman** [comment]
项目已经停止维护了

**Comment by zuishikonghuan** [comment]
@akkuman 好吧，我再等一段时间，如果维护者确实已对这个项目失去兴趣，而且没有接盘的人，就退掉宽带好了，还能省几顿饭钱qvq

**Comment by zuishikonghuan** [comment]
已经使用 #188 提供的方法解决

**Comment by zuishikonghuan** [comment]
感谢 #188 ，已经解决
