### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by ultravires** [miao1007/Openwrt-NetKeeper#205]
首先我对有技术的人非常尊重，在路由器风波过去后。我再也不愿意为自己的愚蠢付费。所以我开始研究一些原理。目前我在分析一款py打包好的软件，但是在运行的时候遇到了各种问题。我想知道如何根据打包好的程序配置py运行环境。希望不吝赐教，谢谢~！

**Comment by miao1007** [comment]
从买一本Python从入门到精通开始
