### ISSUE TITLE
河北联通的radius 是什么

### ISSUE THREAD

**Issue by mumuhhh** [miao1007/Openwrt-NetKeeper#25]
河北联通的radius 是什么netkeeper加了壳  搞了半天始终找不到河北联通的radius

**Comment by miao1007** [comment]
发个安装包，最好能有多个平台的

**Comment by mumuhhh** [comment]
邮箱是什么？

**Comment by mumuhhh** [comment]
已发到邮箱

**Comment by mumuhhh** [comment]
。。。。。邮件被退回。。。。

**Comment by mumuhhh** [comment]
Unfortunately, we don’t support that file type.  Try again with a PNG, GIF, JPG.

**Comment by mumuhhh** [comment]
我勒个去  邮件发不过去  这也贴不了附件
Unfortunately, we don’t support that file type.  Try again with a PNG, GIF, JPG.

**Comment by mumuhhh** [comment]
那你谷歌邮箱我发邮件发不过去

**Comment by mumuhhh** [comment]
邮件发不了了

**Comment by mumuhhh** [comment]
发个百度网盘共享http://pan.baidu.com/s/12VTVo

**Comment by realityone** [comment]
```
# .data:005800E4 00000021 C eb1ab586d3b5f22fe4680c5b98471049
```

**Comment by mumuhhh** [comment]
？？加密字符?

**Comment by mumuhhh** [comment]
感谢realityone    用你的XLStringEnc.py解出了radius
hebeicncxinli002

**Comment by mumuhhh** [comment]
你是怎么找出radius的  我怎么始终找不到

**Comment by mumuhhh** [comment]
pull requests 没人理？？

**Comment by miao1007** [comment]
哪有那么多时间维护.... 找到工作再说，你先pull就是
