### ISSUE TITLE
WNDR4300能用这个吗？

### ISSUE THREAD

**Issue by syseric** [miao1007/Openwrt-NetKeeper#3]
WNDR4300 CPU不是AR71XX  但OPENWRT官网固件把他分到AR71XX里面，那能不能用这个呢？如果不能的话，哪里能找到WNDR4300 GCC啊？

**Comment by miao1007** [comment]
它是AR9344的，可以使用，搜索ar9344gcc就有

**Comment by syseric** [comment]
感谢回复，但我实在是没找到在哪儿下载  能帮忙找下吗？
