### ISSUE TITLE
编译心跳插件出错了

### ISSUE THREAD

**Issue by Cheukfung** [miao1007/Openwrt-NetKeeper#49]
编译daonet里面打插件失败，错误信息是：
/home/cheukfung/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/bin/mips-openwrt-linux-gcc  -o DaoNet main.o frame.o netutils.o netkeeper.o /home/cheukfung/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/lib/libmbedcrypto.a -g -Wall -Wimplicit-function-declaration -I /home/cheukfung/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/include/ 
mips-openwrt-linux-gcc: error: /home/cheukfung/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/lib/libmbedcrypto.a: No such file or directory
make: **\* [DaoNet] 错误 1
我是菜鸟。。在lib目录下面只找到libcrypto.a，是库的原因吗，希望能解决，谢谢。

**Comment by xseven007** [comment]
这个是mbed TLS 的library文件，并不是openssl的。你可以考虑编译一个mbedtls。

**Comment by CheukFung** [comment]
谢谢你的回复。我用openwrt编译的SDK编译了mbedtls，然后成功编译出DaoNet，可是在openwrt上面不能运行，只显示not found，我是否遗漏了什么？

**Comment by xseven007** [comment]
编译的时候是否使用了动态库？

**Comment by CheukFung** [comment]
应该没有，我不是很懂。能详细点吗？或者你可以编译一个ar71的心跳插件给我吗？谢谢。。现在20分钟必断网

**Comment by Whatnamegood** [comment]
@CheukFung 你是怎么编译mbedtls的？  有的是哪个版本哦？

**Comment by CheukFung** [comment]
@Whatnamegood 用下载的gcc编译mbedtls，然后放到lib文件夹

**Comment by Whatnamegood** [comment]
@CheukFung 怎么用下载GCC编译呢？直接设置环境变量吗？

**Comment by Whatnamegood** [comment]
[root@localhost DaoNet]# make
mips-openwrt-linux-gcc  -o DaoNet main.o frame.o netutils.o netkeeper.o /home/li/Open/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libmbedcrypto.a -g -Wall -Wimplicit-function-declaration -I /home/li/Open/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include/
/home/li/Open/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: /home/li/Open/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libmbedcrypto.a(aes.o): Relocations in generic ELF (EM: 62)
/home/li/Open/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: /home/li/Open/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libmbedcrypto.a(aes.o): Relocations in generic ELF (EM: 62)
/home/li/Open/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libmbedcrypto.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make: *** [DaoNet] 错误 1
[root@localhost DaoNet]#

**Comment by Whatnamegood** [comment]
这里是说libmbedcrypto.a 文件类型错误    那也就是说编译时没有用到交叉编译的gcc

**Comment by Whatnamegood** [comment]
@CheukFung 你好

**Comment by CheukFung** [comment]
@Whatnamegood 修改mbedtls下library下的makefile，添加CC=xxxx，xxxx为你下载的gcc路径，然后make就可以了。

**Comment by Whatnamegood** [comment]
@CheukFung 谢谢你   我已经成功编译了   可是要怎么使用呢？
 root@OpenWrt:~# DaoNet
WARRNING: Support for ShanXi Netkeeper temporary.
Missing arguments.
Usage: daonet [OPTIONS]
Options:
  --username,  -u:      Username.
  --password,  -p:      Password.
  --ipaddress, -i:      IP Address.
  --version,   -v:      Version.
  --aeskey,    -k:      Aes key.
  --interval,  -I:      Interval.
  --target,    -t:      Target.
  --port,      -P:      Port.
  --help,      -h:      Help.
root@OpenWrt:~#


这里是要填写其配置文件？  还是要在编译是把账号信息写入到源码在编译？  或者接选项-u -p 然后接参数执行呢？

**Comment by sunflyer** [comment]
直接带参数执行。注意ip地址是你拨号获得的ip

**Comment by Whatnamegood** [comment]
能给个实例吗？

**Comment by Whatnamegood** [comment]
@sunflyer

**Comment by sunflyer** [comment]
DaoNet -u <宽带账号> -p <密码> -i <你拨号获得的IP地址> -v 2.5.0016v32 -k wanglibinwanglei -I 120 -t 117.21.209.186 -P 443

**Comment by Whatnamegood** [comment]
谢谢！   这里的-k 的key 是固定吗   是不是各个地区的都不同？

**Comment by Whatnamegood** [comment]
王立彬王雷？

**Comment by Whatnamegood** [comment]
root@OpenWrt:~# ./daonet.sh
root@OpenWrt:~# WARRNING: Support for ShanXi Netkeeper temporary.
INFO: Send packet succeed.
ERROR: Wait for packet timeout.
INFO: Wait 120 seconds.


这样是正常的吗？ ERROR: Wait for packet timeout.

**Comment by sunflyer** [comment]
没事，江西没有回复包，正常

**Comment by smounives** [comment]
@sunflyer 湖北E信可以使用这个心跳插件吗？需不需要改什么？

**Comment by sunflyer** [comment]
湖北不能

**Comment by smounives** [comment]
QAQ 难道只能直接插网线用您的SimpleNetkeeper了吗

**Comment by sunflyer** [comment]
最快下周出op支持吧，看情况

**Comment by smounives** [comment]
多谢！

**Comment by theflash2017** [comment]
您好，请问您有空吗？我想编译一个daonet但是并不会，您能指导一下吗？
