### ISSUE TITLE
Not special client是什么错误

### ISSUE THREAD

**Issue by Cheukfung** [miao1007/Openwrt-NetKeeper#52]
Sun Nov  1 20:17:15 2015 daemon.info pppd[7360]: Remote message: [Code 13|2]: Not special client
Sun Nov  1 20:17:15 2015 daemon.err pppd[7360]: PAP authentication failed
Sun Nov  1 20:17:15 2015 daemon.notice pppd[7360]: Modem hangup
Sun Nov  1 20:17:15 2015 daemon.notice pppd[7360]: Connection terminated.
Sun Nov  1 20:17:15 2015 daemon.info pppd[7360]: Sent PADT
Sun Nov  1 20:17:15 2015 daemon.info pppd[7360]: Exit.
请问这是什么错误？断开连接之后再连偶尔会出现的错误

**Comment by sunflyer** [comment]
错误信息显示用户不存在。可能是电信的问题
