### ISSUE TITLE
能否支持广东广州的Young网络客户端

### ISSUE THREAD

**Issue by matthew728960** [miao1007/Openwrt-NetKeeper#56]
我把客户端上传了，请帮忙，谢谢！（打开时请将png改为zip）（HC5761-MT7620A）
https://cloud.githubusercontent.com/assets/8460881/10959876/e80fb610-83b8-11e5-9339-c17c92895885.png
如果可以说一下怎么手动上传就更好了，而不是make upload，毕竟不是每个人都有Ubuntu。感谢

**Comment by sunflyer** [comment]
这个似乎并不是Netkeeper系列，

**Comment by matthew728960** [comment]
这样啊，那你知不知道这种有什么方法登陆呢，谢谢！！

**Comment by milkyfox** [comment]
@sunflyer 
请问这个是否为 Netkeeper 系列
http://www.wandoujia.com/apps/com.xinli.portalclient

**Comment by sunflyer** [comment]
这个是，你是哪个地区的

**Comment by milkyfox** [comment]
@sunflyer 山东，电信校园网。连上 WiFi 会弹出这个网址来下载客户端
http://219.146.3.54:8080
这个可以添加支持吗？

**Comment by sunflyer** [comment]
山东电信的radius我之前解了一次似乎和陕西的是一样的，你试下看

**Comment by milkyfox** [comment]
@sunflyer 谢谢，我试试

**Comment by milkyfox** [comment]
@sunflyer 请问 radius 是 sh_do@xiaoyuan01 吗？

sh_xi@xiaoyuan01 >> sh_do@xiaoyuan01

**Comment by sunflyer** [comment]
不是，就直接和陕西一样的，不用改

**Comment by milkyfox** [comment]
@sunflyer 似乎不是 sh_xi@xiaoyuan01
电脑上用天翼客户端拨号和用 SimpleNetkeeper_Win 算出来的账号不一样
![image](https://cloud.githubusercontent.com/assets/7358341/11303160/6732e7e4-8fdc-11e5-9de6-f868a652c7b7.png)
手机号前的两位不一样

**Comment by sunflyer** [comment]
shdOx!a0yuan01lz

你试下是不是这个？

**Comment by milkyfox** [comment]
@sunflyer 手机号前两位还是不一样...

**Comment by sunflyer** [comment]
你直接复制过去，注意不要多了空格。最好是用测试功能的自定义radius试试
前缀\r\n

**Comment by milkyfox** [comment]
@sunflyer 
![image](https://cloud.githubusercontent.com/assets/7358341/11317643/bcebbe52-906f-11e5-87ea-dda4d1d43f6f.png)
![image](https://cloud.githubusercontent.com/assets/7358341/11317644/c2f89d6a-906f-11e5-9da5-e25b1ab73e74.png)
radius 没有空格

**Comment by sunflyer** [comment]
鸭血，这尼玛什么情况。。。dump出来的确是这个啊，你用的3.7.3么

**Comment by milkyfox** [comment]
@sunflyer 是 3.7.3

**Comment by sunflyer** [comment]
然而我从3.7.3拿到的就是这个。。。回去再看看吧。。。

**Comment by milkyfox** [comment]
@sunflyer 呃，有两个 3.7.3 版本，10 月 17 号那个我输上密码显示密码错误
![image](https://cloud.githubusercontent.com/assets/7358341/11318300/d98154de-9086-11e5-9a85-c21ca1ec4424.png)

这个是 8 月 17 号的版本，可以登录
http://jianguoyun.com/p/DXus_kIQwobeBRi7kQ8
可否再试试

**Comment by sunflyer** [comment]
我开始是从10月哪个版本抓的。。。等下试试8月的

**Comment by milkyfox** [comment]
@sunflyer 谢谢！

**Comment by sunflyer** [comment]
radius = 560Ox!a0yuanOlIz
怎么都是些莫名其妙的玩意儿。。。。。

**Comment by milkyfox** [comment]
@sunflyer 
![image](https://cloud.githubusercontent.com/assets/7358341/11319376/89a0352e-90af-11e5-9a6e-7a91875b33ec.png)
 谢谢！！

**Comment by sunflyer** [comment]
那么这个radius是对的咯

**Comment by milkyfox** [comment]
@sunflyer 嗯，是对的
