### ISSUE TITLE
河北地区拨号问题

### ISSUE THREAD

**Issue by opUserZangYing** [miao1007/Openwrt-NetKeeper#58]
编译正常，上传正常
pppd是2.4.5已改
但是无法联网，有什么办法看原因吗？
是否需要把 \n 改成 \r\n？

**Comment by sunflyer** [comment]
把系统日志发上来

**Comment by opUserZangYing** [comment]
我错了……make的时候有一个STAGING-DIR未设置……还有pppd是直接在MAKEfile里改吗？

**Comment by sunflyer** [comment]
不是。。。我是说op的系统日志
另外ppp版本因该是makefile或者c文件里面，有的话就改咯

**Comment by opUserZangYing** [comment]
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    0.000000] env[1]: initrd_start=0x00000000
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    0.000000] env[2]: initrd_size=0x0
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    0.000000] env[3]: flash_start=0xBF000000
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    0.000000] env[4]: flash_size=0x400000
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.000000] bootconsole [early0] enabled
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.000000] CPU revision is: 0001964c (MIPS 24KEc)
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.000000] Ralink RT3052 id:1 rev:3 running at 384.00 MHz
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.000000] Determined physical RAM map:
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.000000]  memory: 02000000 @ 00000000 (usable)
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.000000] Initrd not found or empty - disabling initrd
Nov 17 18:25:03 OpenWrt kern.warn kernel: [    0.000000] Zone PFN ranges:
Nov 17 18:25:03 OpenWrt kern.warn kernel: [    0.000000]   Normal   0x00000000 -> 0x00002000
Nov 17 18:25:03 OpenWrt kern.warn kernel: [    0.000000] Movable zone start PFN for each node
Nov 17 18:25:03 OpenWrt kern.warn kernel: [    0.000000] Early memory PFN ranges
Nov 17 18:25:03 OpenWrt kern.warn kernel: [    0.000000]     0: 0x00000000 -> 0x00002000
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    0.000000] On node 0 totalpages: 8192
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    0.000000] free_area_init_node: node 0, pgdat 802547a0, node_mem_map 81000000
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    0.000000]   Normal zone: 64 pages used for memmap
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    0.000000]   Normal zone: 0 pages reserved
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    0.000000]   Normal zone: 8128 pages, LIFO batch:0
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    0.000000] pcpu-alloc: [0] 0 
Nov 17 18:25:03 OpenWrt kern.warn kernel: [    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 8128
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.000000] Kernel command line:  board=DIR-615-D console=ttyS1,57600 mtdparts=physmap-flash.0:192k(u-boot)ro,64k(devdata)ro,64k(devconf)ro,896k(kernel),2880k(rootfs),3776k@0x50000(firmware) rootfstype=squashfs,jffs2
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.000000] PID hash table entries: 128 (order: -3, 512 bytes)
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.000000] Dentry cache hash table entries: 4096 (order: 2, 16384 bytes)
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.360000] msgmni has been set to 57
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.360000] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 254)
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.380000] io scheduler noop registered
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.390000] io scheduler deadline registered (default)
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.400000] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.410000] serial8250: ttyS0 at MMIO 0x10000500 (irq = 13) is a 16550A
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.430000] serial8250: ttyS1 at MMIO 0x10000c00 (irq = 20) is a 16550A
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.450000] physmap platform flash device: 00800000 at bf000000
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.460000] physmap-flash.0: Found 1 x16 devices at 0x0 in 16-bit bank. Manufacturer ID 0x000001 Chip ID 0x0022f9
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    0.480000] physmap-flash.0: Found an alias at 0x400000 for the chip at 0x0
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.480000] Amd/Fujitsu Extended Query Table at 0x0040
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.490000]   Amd/Fujitsu Extended Query version 1.1.
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.500000] number of CFI chips: 1
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.510000] 6 cmdlinepart partitions found on MTD device physmap-flash.0
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.520000] Creating 6 MTD partitions on "physmap-flash.0":
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.540000] 0x000000000000-0x000000030000 : "u-boot"
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.550000] 0x000000030000-0x000000040000 : "devdata"
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.560000] 0x000000040000-0x000000050000 : "devconf"
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.570000] 0x000000050000-0x000000130000 : "kernel"
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.590000] 0x000000130000-0x000000400000 : "rootfs"
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.600000] mtd: partition "rootfs" set to be root filesystem
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.610000] mtd: partition "rootfs_data" created automatically, ofs=2F0000, len=110000 
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.630000] 0x0000002f0000-0x000000400000 : "rootfs_data"
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.640000] 0x000000050000-0x000000400000 : "firmware"
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.660000] ramips-wdt ramips-wdt: timeout value must be 0 < timeout <= 33, using 33
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.680000] TCP cubic registered
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.690000] NET: Registered protocol family 17
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    0.690000] Bridge firewalling registered
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.700000] 8021q: 802.1Q VLAN Support v1.8
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.720000] VFS: Mounted root (squashfs filesystem) readonly on device 31:4.
Nov 17 18:25:03 OpenWrt kern.info kernel: [    0.730000] Freeing unused kernel memory: 176k freed
Nov 17 18:25:03 OpenWrt kern.info kernel: [    2.520000] input: gpio-keys-polled as /devices/platform/gpio-keys-polled/input/input0
Nov 17 18:25:03 OpenWrt kern.info kernel: [    2.610000] Button Hotplug driver version 0.4.1
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    2.660000] Registered led device: d-link:amber:status
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    2.670000] Registered led device: d-link:green:status
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    2.670000] Registered led device: d-link:amber:wan
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    2.670000] Registered led device: d-link:green:wan
Nov 17 18:25:03 OpenWrt kern.debug kernel: [    2.670000] Registered led device: d-link:blue:wps
Nov 17 18:25:03 OpenWrt kern.notice kernel: [    5.890000] JFFS2 notice: (370) jffs2_build_xattr_subsystem: complete building xattr subsystem, 19 of xdatum (1 unchecked, 18 orphan) and 28 of xref (0 dead, 20 orphan) found.
Nov 17 18:25:03 OpenWrt kern.info kernel: [    7.510000] Compat-drivers backport release: compat-drivers-2012-09-04-2-gddac993
Nov 17 18:25:05 OpenWrt kern.info kernel: [   12.800000] device eth0.1 entered promiscuous mode
Nov 17 18:25:05 OpenWrt kern.info kernel: [   12.810000] device eth0 entered promiscuous mode
Nov 17 18:25:05 OpenWrt kern.info kernel: [   12.830000] br-lan: port 1(eth0.1) entered forwarding state
Nov 17 18:25:05 OpenWrt kern.info kernel: [   12.840000] br-lan: port 1(eth0.1) entered forwarding state
Nov 17 18:25:05 OpenWrt daemon.notice netifd: Interface 'lan' is now up
Nov 17 18:25:05 OpenWrt daemon.notice netifd: Interface 'loopback' is now up
Nov 17 18:25:05 OpenWrt daemon.notice netifd: Interface 'netkeeper' is now up
Nov 17 18:25:05 OpenWrt daemon.notice netifd: Interface 'wan' is now up
Nov 17 18:25:07 OpenWrt user.notice ifup: Enabling Router Solicitations on lan (br-lan)
Nov 17 18:25:07 OpenWrt kern.info kernel: [   14.840000] br-lan: port 1(eth0.1) entered forwarding state
Nov 17 18:25:08 OpenWrt kern.warn kernel: [   15.650000] ramips-wdt: timeout value 60 must be 0 < timeout <= 33, using 33
Nov 17 18:25:10 OpenWrt user.notice ifup: Enabling Router Solicitations on wan (eth0.2)
Nov 17 18:25:10 OpenWrt kern.info kernel: [   17.890000] cfg80211: Calling CRDA for country: US
Nov 17 18:25:11 OpenWrt kern.info kernel: [   17.900000] cfg80211: Regulatory domain changed to country: US
Nov 17 18:25:11 OpenWrt kern.info kernel: [   17.910000] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp)
Nov 17 18:25:11 OpenWrt kern.info kernel: [   17.930000] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2700 mBm)
Nov 17 18:25:11 OpenWrt kern.info kernel: [   17.940000] cfg80211:   (5170000 KHz - 5250000 KHz @ 40000 KHz), (300 mBi, 1700 mBm)
Nov 17 18:25:11 OpenWrt kern.info kernel: [   17.960000] cfg80211:   (5250000 KHz - 5330000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Nov 17 18:25:11 OpenWrt kern.info kernel: [   17.970000] cfg80211:   (5490000 KHz - 5600000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Nov 17 18:25:11 OpenWrt kern.info kernel: [   17.990000] cfg80211:   (5650000 KHz - 5710000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
Nov 17 18:25:11 OpenWrt kern.info kernel: [   18.000000] cfg80211:   (5735000 KHz - 5835000 KHz @ 40000 KHz), (300 mBi, 3000 mBm)
Nov 17 18:25:14 OpenWrt user.notice ifup: Enabling Router Solicitations on netkeeper (eth0.2)
Nov 17 18:25:14 OpenWrt kern.info kernel: [   21.760000] device wlan0 entered promiscuous mode
Nov 17 18:25:15 OpenWrt kern.info kernel: [   22.570000] br-lan: port 2(wlan0) entered forwarding state
Nov 17 18:25:15 OpenWrt kern.info kernel: [   22.580000] br-lan: port 2(wlan0) entered forwarding state
Nov 17 18:25:17 OpenWrt user.notice ifup: Enabling Router Solicitations on loopback (lo)
Nov 17 18:25:17 OpenWrt kern.info kernel: [   24.580000] br-lan: port 2(wlan0) entered forwarding state
Nov 17 18:25:20 OpenWrt user.info sysinit: Loading defaults
Nov 17 18:25:20 OpenWrt user.info sysinit: Loading synflood protection
Nov 17 18:25:20 OpenWrt user.info sysinit: Adding custom chains
Nov 17 18:25:21 OpenWrt user.info sysinit: Loading zones
Nov 17 18:25:22 OpenWrt user.info sysinit: Loading forwardings
Nov 17 18:25:22 OpenWrt user.info sysinit: Loading rules
Nov 17 18:25:22 OpenWrt user.info sysinit: Loading redirects
Nov 17 18:25:22 OpenWrt user.info sysinit: Loading includes
Nov 17 18:25:22 OpenWrt user.info sysinit: Optimizing conntrack
Nov 17 18:25:22 OpenWrt user.info sysinit: Loading interfaces
Nov 17 18:25:22 OpenWrt user.info firewall: adding lan (br-lan) to zone lan
Nov 17 18:25:23 OpenWrt user.info firewall: adding wan (eth0.2) to zone wan
Nov 17 18:25:24 OpenWrt user.info firewall: adding netkeeper (eth0.2) to zone wan
Nov 17 18:25:26 OpenWrt authpriv.info dropbear[1264]: Running in background
Nov 17 18:25:28 OpenWrt user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Nov 17 18:25:28 OpenWrt user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Nov 17 18:25:32 OpenWrt daemon.info dnsmasq[1318]: started, version 2.62 cachesize 150
Nov 17 18:25:32 OpenWrt daemon.info dnsmasq[1318]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP no-DHCPv6 no-Lua TFTP no-conntrack
Nov 17 18:25:32 OpenWrt daemon.info dnsmasq-dhcp[1318]: DHCP, IP range 192.168.1.100 -- 192.168.1.249, lease time 12h
Nov 17 18:25:32 OpenWrt daemon.info dnsmasq[1318]: using local addresses only for domain lan
Nov 17 18:25:32 OpenWrt daemon.warn dnsmasq[1318]: no servers found in /tmp/resolv.conf.auto, will retry
Nov 17 18:25:32 OpenWrt daemon.info dnsmasq[1318]: read /etc/hosts - 1 addresses
Nov 17 18:25:32 OpenWrt daemon.info dnsmasq-dhcp[1318]: read /etc/ethers - 0 addresses
Nov 17 18:25:32 OpenWrt user.info sysinit: setting up led Status LED (amber)
Nov 17 18:25:32 OpenWrt user.info sysinit: setting up led wifi
Nov 17 19:47:06 OpenWrt daemon.info hostapd: wlan0: STA 78:6c:1c:b5:0c:45 IEEE 802.11: authenticated
Nov 17 19:47:06 OpenWrt daemon.info hostapd: wlan0: STA 78:6c:1c:b5:0c:45 IEEE 802.11: authenticated
Nov 17 19:47:12 OpenWrt daemon.info hostapd: wlan0: STA 78:6c:1c:b5:0c:45 IEEE 802.11: disassociated
Nov 17 19:47:13 OpenWrt daemon.info hostapd: wlan0: STA 78:6c:1c:b5:0c:45 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Nov 17 19:48:37 OpenWrt daemon.info hostapd: wlan0: STA 78:6c:1c:b5:0c:45 IEEE 802.11: authenticated
Nov 17 19:48:37 OpenWrt daemon.info hostapd: wlan0: STA 78:6c:1c:b5:0c:45 IEEE 802.11: associated (aid 1)
Nov 17 19:48:45 OpenWrt daemon.info hostapd: wlan0: STA 78:6c:1c:b5:0c:45 IEEE 802.11: deauthenticated due to local deauth request
Nov 17 19:49:27 OpenWrt daemon.info hostapd: wlan0: STA 78:6c:1c:b5:0c:45 IEEE 802.11: authenticated
Nov 17 19:49:27 OpenWrt daemon.info hostapd: wlan0: STA 78:6c:1c:b5:0c:45 IEEE 802.11: authenticated
Nov 17 19:49:27 OpenWrt daemon.info hostapd: wlan0: STA 78:6c:1c:b5:0c:45 IEEE 802.11: associated (aid 1)
Nov 17 19:49:36 OpenWrt daemon.info hostapd: wlan0: STA 78:6c:1c:b5:0c:45 IEEE 802.11: deauthenticated due to local deauth request
Nov 17 22:39:32 OpenWrt daemon.info hostapd: wlan0: STA 6c:71:d9:0e:a1:7b IEEE 802.11: authenticated
Nov 17 22:39:32 OpenWrt daemon.info hostapd: wlan0: STA 6c:71:d9:0e:a1:7b IEEE 802.11: associated (aid 1)
Nov 17 22:39:32 OpenWrt daemon.info hostapd: wlan0: STA 6c:71:d9:0e:a1:7b WPA: pairwise key handshake completed (RSN)
Nov 17 22:39:36 OpenWrt daemon.info dnsmasq-dhcp[1318]: DHCPDISCOVER(br-lan) 6c:71:d9:0e:a1:7b 
Nov 17 22:39:36 OpenWrt daemon.info dnsmasq-dhcp[1318]: DHCPOFFER(br-lan) 192.168.1.105 6c:71:d9:0e:a1:7b 
Nov 17 22:39:36 OpenWrt daemon.info dnsmasq-dhcp[1318]: DHCPREQUEST(br-lan) 192.168.1.105 6c:71:d9:0e:a1:7b 
Nov 17 22:39:36 OpenWrt daemon.info dnsmasq-dhcp[1318]: DHCPACK(br-lan) 192.168.1.105 6c:71:d9:0e:a1:7b ToBeACracker
Nov 17 22:39:53 OpenWrt authpriv.info dropbear[1500]: Child connection from 192.168.1.105:34916
Nov 17 22:40:03 OpenWrt authpriv.notice dropbear[1500]: Password auth succeeded for 'root' from 192.168.1.105:34916
Nov 17 22:40:05 OpenWrt authpriv.info dropbear[1500]: Exit (root): Disconnect received
Nov 17 22:40:08 OpenWrt authpriv.info dropbear[1506]: Child connection from 192.168.1.105:35091
Nov 17 22:40:17 OpenWrt authpriv.notice dropbear[1506]: Password auth succeeded for 'root' from 192.168.1.105:35091
Nov 17 22:40:20 OpenWrt authpriv.info dropbear[1506]: Exit (root): Disconnect received
Nov 17 22:40:20 OpenWrt authpriv.info dropbear[1509]: Child connection from 192.168.1.105:35213
Nov 17 22:40:27 OpenWrt authpriv.notice dropbear[1509]: Password auth succeeded for 'root' from 192.168.1.105:35213
Nov 17 22:40:28 OpenWrt authpriv.info dropbear[1509]: Exit (root): Disconnect received
Nov 17 22:40:28 OpenWrt authpriv.info dropbear[1512]: Child connection from 192.168.1.105:35281
Nov 17 22:40:36 OpenWrt authpriv.notice dropbear[1512]: Password auth succeeded for 'root' from 192.168.1.105:35281
Nov 17 22:40:50 OpenWrt user.info firewall: adding lan (br-lan) to zone lan
Nov 17 22:40:51 OpenWrt user.info firewall: adding wan (eth0.2) to zone wan
Nov 17 22:40:52 OpenWrt user.info firewall: adding netkeeper (eth0.2) to zone wan
Nov 17 22:40:58 OpenWrt authpriv.info dropbear[1512]: Exit (root): Disconnect received
Nov 18 10:19:30 OpenWrt daemon.info hostapd: wlan0: STA 6c:71:d9:0e:a1:7b WPA: group key handshake completed (RSN)
Nov 18 10:29:14 OpenWrt daemon.info hostapd: wlan0: STA 6c:71:d9:0e:a1:7b IEEE 802.11: authenticated
Nov 18 10:29:14 OpenWrt daemon.info hostapd: wlan0: STA 6c:71:d9:0e:a1:7b IEEE 802.11: associated (aid 1)
Nov 18 10:29:14 OpenWrt daemon.info hostapd: wlan0: STA 6c:71:d9:0e:a1:7b WPA: pairwise key handshake completed (RSN)
Nov 18 10:29:14 OpenWrt daemon.info dnsmasq-dhcp[1318]: DHCPDISCOVER(br-lan) 6c:71:d9:0e:a1:7b 
Nov 18 10:29:14 OpenWrt daemon.info dnsmasq-dhcp[1318]: DHCPOFFER(br-lan) 192.168.1.105 6c:71:d9:0e:a1:7b 
Nov 18 10:29:14 OpenWrt daemon.info dnsmasq-dhcp[1318]: DHCPREQUEST(br-lan) 192.168.1.105 6c:71:d9:0e:a1:7b 
Nov 18 10:29:14 OpenWrt daemon.info dnsmasq-dhcp[1318]: DHCPACK(br-lan) 192.168.1.105 6c:71:d9:0e:a1:7b ToBeACracker-PC
Nov 18 10:29:30 OpenWrt daemon.info hostapd: wlan0: STA 6c:71:d9:0e:a1:7b WPA: group key handshake completed (RSN)

**Comment by sunflyer** [comment]
你的日志里面没有任何拨号记录。

**Comment by opUserZangYing** [comment]
3Q----刷了个15.05的OP再试就好了----

**Comment by hong0980** [comment]
求个ppp2.4.5.的源码，谢谢！hong0980@qq.com
