### ISSUE TITLE
畅通无线keeper什么原理

### ISSUE THREAD

**Issue by mumuhhh** [miao1007/Openwrt-NetKeeper#59]
太多人用我的路由  ，我快疯了

**Comment by sunflyer** [comment]
设置dhcp的ip段，然后把你自己的手机电脑设置到不在ip段的ip(比如你ip段默认100-200，你就把自己的ip设置成1-99)，用路由器的静态地址保留加mac绑定，然后直接开限速，指定ip段，差不多就行了

至于畅通无线那个，走的portal
