### ISSUE TITLE
江西电信又更新了，旧版无法使用

### ISSUE THREAD

**Issue by lknife** [miao1007/Openwrt-NetKeeper#71]
新版下载地址
http://117.21.211.4/apps/NKSetup4.6.6.561.exe
求跟进破解，广大江西人民感激不尽

**Comment by sunflyer** [comment]
NK4.6已经更换算法，目前无解。。。。。。

**Comment by lknife** [comment]
以后有可能破解吗

**Comment by sunflyer** [comment]
这东西要看以后了。。。。。。至少这个学期可能不现实。（但愿我会被这个flag打脸）

**Comment by miao1007** [comment]
目前应该不会了
